baseurl = "/"
languageCode = "en-us"
title = "Forza Football Brand Style Guide"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Forza Football"
	description = "Branding styling guidelines."
	copyright = "All rights reserved"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
      text = "Roboto"
      code = "Roboto Mono"


[social]
	twitter = "forzafootball"
	github  = ""
	email   = "hello@email.com"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Identity"
	url    = "identity/"
	weight = 20

[[menu.main]]
	name   = "Fonts & Colors"
	url    = "fonts-colors/"
	weight = 30

[[menu.main]]
	name   = "Examples"
	url    = "examples/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
